### ISSUE TITLE
Scraping crashes after scraping.

### ISSUE THREAD

**Issue by dekoma4u** [Seb943/scrapeOP#6]
After scraping, I get this error message, 

/Users/ugooezekoma/code/dekoma4u/ebetting/ugoo/scrapeOP
Data will be saved in the following directory: /Users/ugooezekoma/code/dekoma4u/ebetting/ugoo/scrapeOP
We start to collect current season
We start to scrape the page n°1
[]
Function crashed, probable reason : no games scraped (empty season)
We finished to collect current season !
Traceback (most recent call last):
  File "FinalScraper.py", line 19, in <module>
    scrape_oddsportal_historical(sport = 'esports', country = 'world', league = 'counter-strike-esl-pro-league-season-16', start_season = '2022', nseasons = 0, current_season = 'yes', max_page = 2)
  File "/Users/ugooezekoma/code/dekoma4u/ebetting/ugoo/scrapeOP/functions.py", line 1323, in scrape_oddsportal_historical
    df = scrape_league_typeA(Season = start_season, sport = sport, country1 = country, tournament1 = league, nseason = nseasons, current_season = 'yes', max_page = max_page)
  File "/Users/ugooezekoma/code/dekoma4u/ebetting/ugoo/scrapeOP/functions.py", line 326, in scrape_league_typeA
    file1 = pd.read_csv('./{}/'.format(tournament1) + os.listdir('./{}/'.format(tournament1))[0], sep=';')
FileNotFoundError: [Errno 2] No such file or directory: './counter-strike-esl-pro-league-season-16/'

Can you please have a look and help me fix this as soon as possible?

**Comment by Seb943** [comment]
Hi,
A new version was released today.
The package is now adapted to the latest version of pandas, and corrects a few bugs related to cookies.

Hoping it solves your problem.
Feel free to open a new issue if the new version still contains your bug.
